### ISSUE TITLE
Problem with show-paren-mode on unchanged hunks

### ISSUE THREAD

**Issue by kriansa** [emacsorphanage/git-gutter#150]
This is related to #114 and #115. When using `git-gutter` + `show-paren-mode`, it highlights the gutter with a weird color, but only on "unchanged" hunks.

![image](https://user-images.githubusercontent.com/962032/31941838-03f925e4-b8a2-11e7-874e-6179ae07d4fd.png)

I fixed that by copying your fix on #115:

```lisp
(set-face-attribute 'git-gutter:unchanged nil :background nil :inherit 'default)
```

I'm not sure if this is a real fix, that's why I'm not opening a pull-request.

Thank you @syohex for this awesome package!

**Comment by gonewest818** [comment]
That will be easy enough to change.  Thank you for reporting!

**Comment by gonewest818** [comment]
I'm merging a fix for this; but note my default theme (zenburn) also overrides the definition of these faces, and while testing I temporarily disabled my theme to make sure I was seeing things the way the package intends.

**Comment by kriansa** [comment]
This is awesome. Thanks @gonewest818 !
