### ISSUE TITLE
Git gutter freeze for a few seconds on first load

### ISSUE THREAD

**Issue by benwainwright** [emacsorphanage/git-gutter#163]
When I use git-gutter, as soon as I scroll to a part of the file where there are any differences, I get an immediate 1-3 second freeze the very first time. This has made the package unusable to me so I'm using diff-hl for now even though I'd prefer not to. Anyone got any ideas how to debug this?

**Comment by gonewest818** [comment]
You can use the built-in profiler commands `profiler-start`, `profiler-report`, and `profiler-stop`.

So for instance, do `M-x profiler-start`. Then open a file. Scroll to a place where there are diffs. Assuming you get the 3 second pause, then type `M-x profiler-report` and you'll see a new buffer that shows where the time was spent.  Type `M-x profiler-stop` to stop the profiler from measuring any further.
