### ISSUE TITLE
README + MELPA should clearly state project is unmaintained

### ISSUE THREAD

**Issue by aspiers** [emacsorphanage/git-gutter#171]
According to https://github.com/emacsorphanage/emacs-git-gutter/issues/151#issuecomment-599181324 this package is no longer maintained, but this is not at all clear from the `README.md`, nor from http://stable.melpa.org/#/git-gutter.

It's also not clear why some issues are being closed but others left open.  It would be much more helpful to newcomers if `README.md` and MELPA clearly explain the status of the package.

**Comment by manuel-uberti** [comment]
See: https://github.com/melpa/melpa/issues/6674

Along with other projects from the same author, this has been handed over new maintainers.

**Comment by aspiers** [comment]
Thanks a lot for the info @manuel-uberti.  In that case I wonder why @syohex closed #151 and declared the package unmaintained.  It seems there is some confusion here.

**Comment by syohex** [comment]
Update README 07297cf0e92593422def5bae82d95ee79bdfc3b6

**Comment by gonewest818** [comment]
Indeed, now that the project(s) are transferred to emacsorphanage the ownership can be delegated to new maintainers. 

@purcell can you modify the "this package is no longer maintained" comment in the README and replace it with something like "this package is temporarily in the care of emacsorphanage, and will be transferred to new maintainer(s) shortly?"

**Comment by tarsius** [comment]
@aspiers This package has been unmaintained for a few years or so. You made this request at the worst possible time during those years at the *very* end, while (after several years of inactivity) we were actively working on getting things back on track again. @syohex who has previously fallen silently before was actively responding to my requests, even within minutes. And then you opened this issue and he responded immediately by taking the appropriate action. And @gonewest818 finds that even more confusing and requests that I write some other status report to be used for the next 12-48 hours. The best summary that we can have during this time is the same summary we use for most of the other packages in the Emacs orphanage: no summary, while hoping the use of the term `orphanage` conveys enough meaning.

I therefore respond to this request by reverting the previous commit by @syohex and hoping we can just all be a bit patient. What's a day or two after a few years? I was actually just gonna ignore this issue, but found myself laying in bed thinking about how to formulate a response. So I got up again and did.

**Comment by gonewest818** [comment]
Fair enough. Thanks and sorry to have disrupted your sleep for this, that obviously wasn't my intention at all.

**Comment by aspiers** [comment]
Thanks a lot @tarsius for the explanation. Please know that I had zero clue about any of that context, so my bad timing was purely bad luck. Of course I'm happy to wait as long as necessary.  I was just reporting what appeared like a confusing situation from the outside. Great to hear that it's already transitioning to a better place. Thanks again everyone for your work on Emacs!

**Comment by tarsius** [comment]
I wasn't trying to suggest otherwise.
