### ISSUE TITLE
[Bug] Undo fails to update the gutter

### ISSUE THREAD

**Issue by ianpan870102** [emacsorphanage/git-gutter#172]
Let me start by saying a big thank-you for creating this package (along with the fringe version)!!

**Bug description**
For example, if I made a change to a certain line, the gutter would turn blue to respect the change. However, when I hit undo, the blue gutter stays there.

The expected behaviour would be that the gutter disappears after the undo is invoked, as no change has technically been made.

Currently, the blue gutter will eventually disappear if I revert the buffer.

**Comment by syohex** [comment]
Because `undo` does not save buffer. I suppose you should use live-update feature, if it is enabled, gutter information updates per some seconds.

```lisp
(custom-set-variables
 '(git-gutter:update-interval 2)) ;; update gutter information per 2 seconds.
```

Or use such ugly hack(I don't recommend)

```lisp
(advice-add #'undo :after #'save-buffer)
```

**Comment by ianpan870102** [comment]
Thx for the reply -- actually I do have live-update enabled.
Here's my config (should've posted it in the first place)

```emacs-lisp
(use-package git-gutter
  :hook (prog-mode . git-gutter-mode)
  :config
  (setq git-gutter:update-interval 0.05))
```

**Comment by ianpan870102** [comment]
The issue persists even live-update is suppose to update the gutter every 0.05 second

**Comment by gonewest818** [comment]
It looks like the live update checks `buffer-modified-p`, and if nil (no changes) then the live update aborts and doesn't update the gutter at all.

As a quick test, can you make two changes in the buffer and then undo just one of the two?

**Comment by ianpan870102** [comment]
I just tested with 2, or 3 or more changes and undoing them all. The oldest/first change (i.e. last undo) will always persist with a coloured gutter.

> can you make two changes in the buffer and then undo just one of the two?

Sure, in this case the most recent change's gutter will be gone, but the oldest (first) change's gutter persists. And as I mentioned above, the older gutter will still persist after my second undo.

Hope this gives a good overview.

**Comment by gonewest818** [comment]
Thanks, that’s consistent with expectations.

What that proves is that the gutter drawing code can’t simply abort when the buffer is unchanged. What’s happening is we never get a chance to erase the last gutter marker after the user has reverted the last change in the buffer.

**Comment by ianpan870102** [comment]
I see. Thanks for the insight. Apart from this (relatively minor) issue, the package is otherwise perfect for my daily use.
I'm actually surprised that checking vc info every 0.05 second (as I configured it) didn't produce any visible performance drop in Emacs.

**Comment by gonewest818** [comment]
Great.  I think 0.05 is probably overkill, but what it suggests is we might be able to compute diffs more frequently and without resorting to a timer.  For instance, I want to experiment with scheduling a diff every time the cursor moves to a new line, every time the current buffer changes, and every time the window layout changes.

**Comment by ianpan870102** [comment]
Friendly ping: any updates on this issue?

**Comment by gonewest818** [comment]
I'm sorry, right now my day job is occupying nights also -- still on my todo list to explore triggering the diffs more frequently. I don't have much code invested there (only research) so if someone else wants to give it a try I would appreciate the pull request!

Otherwise, I appreciate your patience.  Thanks all
