### ISSUE TITLE
Maintain issue

### ISSUE THREAD

**Issue by jcs090218** [emacsorphanage/git-gutter#183]
I think @gonewest818 is maintaining this package? I guess he may be busy recently since from his last commit on March 27.

@tarsius I would also like to help maintain this package. Would you mind giving me the access to this repo? Thank you! 😄

**Comment by gonewest818** [comment]
Busy indeed with the pandemic and work. Thanks for offering to help.

**Comment by jcs090218** [comment]
> Busy indeed with the pandemic and work.

Sorry to hear that! Hope everything is okay!

**Comment by tarsius** [comment]
@jcs090218 That would be great. Thanks! Access granted.
@gonewest818 Good luck!
