### ISSUE TITLE
Setting of git-gutter:unchanged-sign brakes displaying of +, - and modified signs

### ISSUE THREAD

**Issue by samolisov** [emacsorphanage/git-gutter#189]
When the `git-gutter:unchanged-sign` is set in any value but `nil`, the configured as well as default signs for modified, added, deleted lines aren't displayed by git-gutter at all. The overall git-gutter line in the left side of the buffer is filled by the configured `git-gutter:unchanged-sign` symbol (by default just a yellow solid line).

The minimum changes to the configuration to demonstrate the problem:

```emacs-lisp
(custom-set-variables
 '(git-gutter:unchanged-sign " "))
```
(The sign has the same size as configured modified/added/deleted signs, but I tried with the default values for modified/added/deleted signs and it also doesn't work).

All the others values are configured by the instruction in the project's `README.md` file. I tried to enable/disable the following parameters `hide-gutter`, `visual-line`, `separator-sign`, `update-interval` and unfortunately nothing works.

I tried to make the git-gutter to have the same background as the 'display-line-numbers' mode has. Since git-gutter doesn't have a common face (in opposite to the 'line-number' face in the d-l-n mode), the idea to configure the same background for unchanged/modified/added/deleted lines looks interesting but it cannot be implemented since git-gutter changes the background only when a symbol for unchanged lines is configured but when the symbol is configured, no other symbols can be displayed.

**Comment by syohex** [comment]
![git-gutter](https://user-images.githubusercontent.com/554281/105199423-16b88680-5b82-11eb-997a-a349f59f0062.gif)

I can't reproduce with following configuration.

```lisp
(require 'git-gutter)
(global-git-gutter-mode +1)
(setq git-gutter:unchanged-sign " ")
```

**Comment by samolisov** [comment]
Unfortunately, this configuration doesn't work for me. 

I'm also trying:
$ emacs -q

in emacs put your configuration, 3 lines prepending them with

```elisp
(load "package")
(package-initialize)
```

 and execute all of them one by one (C-x C-e).

Unfortunately, I see only the yellow line, git-gutter refreshes when I save the file. Just when I execute

```elisp
(setq git-gutter:unchanged-sign nil)
```
and do M-x git-gutter RET, git-gutter draws my pluses and minuses.

I use GNU Emacs 27.1 on Windows 10.

**Comment by syohex** [comment]
It looks an overlay cannot be overwritten by another overlay on Windows Emacs. I suppose it is necessary to put only unchanged lines instead of every lines as below.

```diff
diff --git a/git-gutter.el b/git-gutter.el
index 39ecdd0..7fe2b4d 100644
--- a/git-gutter.el
+++ b/git-gutter.el
@@ -479,7 +479,13 @@ Argument TEST is the case before BODY execution."
           t)
         (goto-char (point-max)))))
 
-(defun git-gutter:view-for-unchanged ()
+(defun git-gutter:unchanged-line-p (line diffinfos)
+  (cl-loop for info in diffinfos
+           for start = (git-gutter-hunk-start-line info)
+           for end = (git-gutter-hunk-end-line info)
+           never (and (>= line start) (<= line end))))
+
+(defun git-gutter:view-for-unchanged (diffinfos)
   (save-excursion
     (let ((sign (if git-gutter:unchanged-sign
                     (propertize git-gutter:unchanged-sign
@@ -491,7 +497,8 @@ Argument TEST is the case before BODY execution."
           points)
       (goto-char (point-min))
       (while (not (eobp))
-        (push (point) points)
+        (when (git-gutter:unchanged-line-p (line-number-at-pos) diffinfos)
+          (push (point) points))
         (funcall move-fn 1))
       (git-gutter:put-signs sign points))))
 
@@ -637,7 +644,7 @@ Argument TEST is the case before BODY execution."
 
 (defun git-gutter:view-set-overlays (diffinfos)
   (when (or git-gutter:unchanged-sign git-gutter:separator-sign)
-    (git-gutter:view-for-unchanged))
+    (git-gutter:view-for-unchanged diffinfos))
   (save-excursion
     (goto-char (point-min))
     (cl-loop with curline = 1
```

![git-gutter](https://user-images.githubusercontent.com/554281/105716434-24935080-5f62-11eb-9c38-0197bd6f0dcd.gif)

**Comment by samolisov** [comment]
@syohex Thank you very much! I've applied the patch and now git-gutter works as it is designed. Do you have any plan to include the patch in any new version of git-gutter?

**Comment by syohex** [comment]
I'll send PR later.

**Comment by syohex** [comment]
I have sent #190.
