### ISSUE TITLE
git-gutter stopped working in org-mode buffers?

### ISSUE THREAD

**Issue by farynaio** [emacsorphanage/git-gutter#192]
IIRC the git-gutter package used to work with org-mode, but I believe since updated to current it stopped. It still works well with other type of major modes - including fundamental-mode.

I haven't change anything in my config, for ages. Probably I used quite old version before, but it just worked. The mode is activated globally, and active in org-mode buffers but does't show the gutter at all in org.

The variable `git-gutter:disabled-modes` is set to nil.

Any idea what may cause git-gutter not working with org-mode?

**Comment by syohex** [comment]
![a](https://user-images.githubusercontent.com/554281/110233033-bc725a00-7f64-11eb-90f6-292e4048314a.png)


I cannot reproduce. `git-gutter` works with org-mode.

- Could you show your environment in more detail ? emacs-version, org-mode version, minimum configuration for reproduce your issue.
- Could you reproduce your issue with minimum configuration ? (For example, disable all configurations other than `git-gutter` and then open org-mode file)

**Comment by farynaio** [comment]
I was able to reproduce it with minimal config. 

To reproduce:
1. create git repo with org file and some text
2. stage and commit
3. add changes to the file in Emacs buffer and save buffer
4. gutter not shows up

```lisp
;; (setq debug-on-error t)
;; (setq debug-on-error nil)

(setenv "SHELL" "/usr/local/bin/bash")
(setq shell-file-name "/bin/sh")

(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/"))
;; (add-to-list 'package-archives '("melpa-stable" . "http://stable.melpa.org/packages/"))
;; (add-to-list 'package-archives '("elpa" . "https://orgmode.org/elpa/"))
;; (add-to-list 'package-archives '("org" . "https://orgmode.org/elpa/"))
;; (add-to-list 'package-archives '("gnu" . "https://elpa.gnu.org/packages/"))

(package-initialize)

(unless package-archive-contents
  (package-refresh-contents))

(setq
 use-package-verbose nil
 use-package-always-ensure t)

(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))

(require 'use-package)

(setq load-prefer-newer t)

(unless (package-installed-p 'org-plus-contrib)
  (package-install 'org-plus-contrib))

(use-package git-gutter
  :custom
  (global-git-gutter-mode +1))
```

Emacs version: GNU Emacs 28.0.50 (build 1, x86_64-apple-darwin19.6.0, NS appkit-1894.60 Version 10.15.7 (Build 19H2))
Org mode version: 9.4.4 (9.4.4-25-g3a522a-elpaplus)
git-gutter: current

**Comment by syohex** [comment]
I got load error if `load-prefer-newer` is non-nil as below.

```
insert-file-contents: Recursive load: "/Applications/Emacs.app/Contents/Resources/lisp/jka-compr.el.gz", "/Applications/Emacs.app/Contents/Resources/lisp/jka-compr.el.gz", "/Applications/Emacs.app/Contents/Resources/lisp/jka-compr.el.gz", "/Applications/Emacs.app/Contents/Resources/lisp/jka-compr.el.gz", "/Applications/Emacs.app/Contents/Resources/lisp/jka-compr.el.gz", "/Applications/Emacs.app/Contents/Resources/lisp/emacs-lisp/package.el.gz"
```

And I cannot reproduce this issue if comment out that line.

![git-gutter](https://user-images.githubusercontent.com/554281/110789684-8100c400-82b3-11eb-9167-0c8a07f5258b.gif)

My environment

```
GNU Emacs 28.0.50 (build 1, x86_64-apple-darwin19.6.0, NS appkit-1894.60 Version 10.15.7 (Build 19H524)) of 2021-03-11
```

**Comment by farynaio** [comment]
How you create a gif attachment?

**Comment by syohex** [comment]
I use licecap https://www.cockos.com/licecap/

**Comment by farynaio** [comment]
I made another test and gutter was shown in all type of buffers. It looks like I have to look for causes of the problems in my own config. Thanks for help @syohex

**Comment by farynaio** [comment]
I found the cause of the problem in another ticket https://github.com/emacsorphanage/git-gutter/issues/193.
