### ISSUE TITLE
Use display-buffer instead of pop-to-buffer

### ISSUE THREAD

**Issue by abcdw** [emacsorphanage/git-gutter#199]
I find `git-gutter:popup-hunk` too agressive, if I open magit or list-buffers or anything else, it occupies the current window, which contains the buffer of my file, but usually it will go to other window.

I adviced git-gutter:popup-hunk to use display-buffer, instead of pop-to-buffer and it started behaving.
```elisp
(defun git-gutter:popup-hunk-new (&optional diffinfo)
  "Popup current diff hunk."
  (interactive)
  (git-gutter:awhen (or diffinfo
                        (git-gutter:search-here-diffinfo git-gutter:diffinfos))
                    (save-selected-window
                      (display-buffer (git-gutter:update-popuped-buffer it)))))

(advice-add 'git-gutter:popup-hunk :override 'git-gutter:popup-hunk-new)
```

Maybe it is also a good idea to change "the defaults" in the package.
https://github.com/emacsorphanage/git-gutter/blob/master/git-gutter.el#L884

Thanks a lot for the package, let me know what you think!)

**Comment by jcs090218** [comment]
Sure thing. Can you open a PR for this? I will accept the change. Thanks! ;)

**Comment by abcdw** [comment]
> Sure thing. Can you open a PR for this? I will accept the
> change. Thanks! ;)

Sent it.
