### ISSUE TITLE
git-gutter does not work in some buffers backed by SVN

### ISSUE THREAD

**Issue by drcxd** [emacsorphanage/git-gutter#216]
Emacs Version 28.1
Platform Windows
Version Control System SVN

Hi, I found that I can not enable git-gutter in some buffers. Git-gutter does work in some buffers backed by git, but it doesn't work in buffers backed by SVN. 

I have not do anything fancy to configure git-gutter. I just enable git-gutter-mode in prog-mode hook. However, when I try `describe-mode` in the buffers where git-gutter seems does not work, I found that it is not enabled as a minor mode. If I try `git-gutter-mode` to toggle it on, a message prompts: "Git-Gutter mode disabled in current buffer". I tried several times, and I found that I simply can not turn on git-gutter-mode in that buffer. There is no other error messages or any other hint.

I also tried diff-hl which works fine.

I do not know elisp much. Could give me some hint that what should I looking for to solve this problem?

I also wants to mention that I have installed `diff` and both `diff` and `svn` are visible in `PATH`.

**Comment by gonewest818** [comment]
Have you enabled svn as a "handled backend"? 
https://github.com/emacsorphanage/git-gutter#backends

**Comment by drcxd** [comment]
> Have you enabled svn as a "handled backend"? https://github.com/emacsorphanage/git-gutter#backends

You are right. I am so sorry that I didn't read the README carefully. Thanks a lot.
