### ISSUE TITLE
Please consider making a melpa-stable release

### ISSUE THREAD

**Issue by laurynas-biveinis** [emacsorphanage/git-gutter#229]
The current version in melpa-stable does not work with 29.1, because it does not have https://github.com/emacsorphanage/git-gutter/pull/222

**Comment by laurynas-biveinis** [comment]
@jcs090218 , something does not appear to be right. A new melpa-stable release 0.92 has been cut, but it is made at commit a33a50c47bebd5d3f9f0ec7e71acf198e5fd4331, which is rather old and certainly does not carry #222

**Comment by jcs090218** [comment]
Made a new release `0.93`.
